[variables]
NIXPACKS_PYTHON_VERSION = '3.9'

[phases.setup]
nixPkgs = ['python39', 'pip', 'ffmpeg']

[phases.install]
cmds = ['pip3 install -r requirements.txt']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'python3 backend/server.py'
